name: Build Geode Mod

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android
            os: ubuntu-latest
            target: Android
            cli_platform: android
          - name: Windows
            os: windows-latest
            target: Windows
            cli_platform: win

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          target: ${{ matrix.config.target }}
        env:
          GEODE_CLI_PLATFORM: ${{ matrix.config.cli_platform }}
